language: elixir
elixir:
  - 1.0.3
  - 1.0.4
otp_release:
  - 17.4
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - export PLT_FILENAME=elixir-${TRAVIS_ELIXIR_VERSION}_$TRAVIS_OTP_RELEASE.plt
  - export PLT_LOCATION=/home/travis/$PLT_FILENAME
  - wget -O $PLT_LOCATION https://raw.github.com/danielberkompas/travis_elixir_plts/master/$PLT_FILENAME
  - mix local.hex --force
  - mix deps.get --only test
script:
  - mix test
  - dialyzer --no_check_plt --plt $PLT_LOCATION -Wno_match -Wno_return --no_native _build/test/lib/ex_twiml/ebin
after_script:
- MIX_ENV=docs mix deps.get
- MIX_ENV=docs mix inch.report
